environment: "development"
service_name: "identity"

# Application Configuration (host and port are here, not in http)
app:
  host: "localhost"
  port: "8080"

# HTTP Server Configuration (no host/port here - different fields)
http:
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 1048576
  allowed_origins: "*"
  allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed_headers: "Content-Type,Authorization"
  exposed_headers: ""
  allow_credentials: true

# Database Configuration (using proper defaults that Viper can handle)
pg:
  host: "localhost"
  port: "5001"
  user: "postgres"
  password: "root"
  database: "postgres"
  ssl_mode: "disable"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 3600
  conn_max_idle_time: 1800

# JWT Configuration (using proper defaults)
jwt:
  secret: "5z4JF/JFOVgC20QTMNyMPeW9kri5mSZ+XHnN9B8a6CmV04jFiCkzyLnbm3IEk5XrCQJm1thcCncK5WOII1GGdF46fwbtakSklUVtUIbfbY4zEcSjBSkbz8vbtRDuEIvm0BYoRHqEHMQoO3O4uwI6WMfIGtphOLiQ6zgl6bDFrF8LKjg6rT/5vJTJiDOjf5dpfWL3Kj5qRwp/MdzR9IGp75tDf9IxaxpJ/dUj/xdlUaBv4Qvlk4829JHBESfvI0PhgvYUWPKC0ZJxZN1/7G1C8VwvMzrzVjViuUccTT3tbrT6z9QWIfzjopRVdWXItpb0wwWO0Wx4oDNR8Mqg32tlkDT1tQNiWbwQQ2Q4hKRkjpk="
  expiration: "15m"
  issuer: "identity-service"
  audience: "identity-users"

# Redis Configuration (using proper defaults)
redis:
  host: "localhost"
  port: "6001"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 3
  dial_timeout: 5
  read_timeout: 3
  write_timeout: 3
  idle_timeout: 300

# Logging Configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: ""
  max_size: 10
  max_backups: 3
  max_age: 28
  compress: true

# Services Configuration for inter-service communication
services:
  identity_service_url: "http://localhost:8080"
  product_service_url: "http://localhost:8081"
  cart_service_url: "http://localhost:8082"
  order_service_url: "http://localhost:8083"
  gateway_service_url: "http://localhost:8000"
  notification_service_url: "http://localhost:8084"
  payment_service_url: "http://localhost:8085"
