environment: "development"
service_name: "gateway"

# Application Configuration (host and port are here, not in http)
app:
  host: "localhost"
  port: "8000"

# HTTP Server Configuration (no host/port here - different fields)
http:
  read_timeout: 10
  write_timeout: 10
  max_header_bytes: 1048576
  allowed_origins: "*"
  allowed_methods: "GET,POST,PUT,DELETE,OPTIONS"
  allowed_headers: "Content-Type,Authorization"
  exposed_headers: ""
  allow_credentials: true

# Logging Configuration
log:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: ""
  max_size: 10
  max_backups: 3
  max_age: 28
  compress: true

# Services Configuration for inter-service communication
services:
  identity_service_url: "http://localhost:8080"
  product_service_url: "http://localhost:8081"
  cart_service_url: "http://localhost:8082"
  order_service_url: "http://localhost:8083"
  gateway_service_url: "http://localhost:8000"
  notification_service_url: "http://localhost:8084"
  payment_service_url: "http://localhost:8085"

# JWT Configuration for token validation (using proper defaults)
jwt:
  secret: "your-secret-key"
  expiration: "24h"
  issuer: "gostore-gateway"
  audience: "gostore-users"
